apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: server
          image: alpine:grpc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SVC_ADDR
              value: "service3:8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            initialDelaySeconds: 20
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          livenessProbe:
            initialDelaySeconds: 20
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          command: ["/src/echoservice/echoservice"]
          volumeMounts:
            - mountPath: /src
              name: src
      volumes:
        - name: src
          hostPath:
            path: /Users/alexyu/go/src/github.com/triplewy/tracing-demo/src
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: ClusterIP
  selector:
    app: service2
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
